packages:
  - apps/*
  - packages/*


onlyBuiltDependencies:
  - '@firebase/util'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - protobufjs
  - re2
  - unrs-resolver

supportedArchitectures:
  os: [current]

