// TODO: Fill in your project name, website URL, and contact email in the marked sections below.

const Policy = () => {
  return (
    <main className='prose prose-lg dark:prose-invert container mx-auto max-w-4xl px-4 py-8'>
      <h1 className='mb-4 text-3xl font-bold'>Privacy Policy</h1>
      <p className='mb-8 text-sm text-gray-600 dark:text-gray-400'>
        Last updated: August 08, 2025
      </p>
      <p>
        This Privacy Policy describes my policies and procedures on the
        collection, use, and disclosure of Your information when You use the
        Service. It also tells You about Your privacy rights and how the law
        protects You.
      </p>
      <p>
        I use Your Personal Data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>

      <h2 className='mt-8 mb-4 text-2xl font-semibold'>
        Interpretation and Definitions
      </h2>
      <h3>Interpretation</h3>
      <p>
        Words with an initial capital letter have meanings defined under the
        following conditions. These definitions have the same meaning regardless
        of whether they appear in singular or plural form.
      </p>
      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul className='mb-6 list-disc space-y-4 pl-6'>
        <li>
          <p>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </p>
        </li>
        <li>
          <p>
            {/* TODO: Change "[Your Project Name]" to your actual project name. */}
            <strong>Developer</strong> (referred to as either "I", "Me", or "My"
            in this Agreement) refers to Sudan Codex.
          </p>
        </li>
        <li>
          <p>
            <strong>Cookies</strong> are small files placed on Your computer or
            device by a website, containing details of Your Browse history.
          </p>
        </li>
        <li>
          <p>
            <strong>Device</strong> means any device that can access the
            Service, such as a computer, a cellphone, or a digital tablet.
          </p>
        </li>
        <li>
          <p>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </p>
        </li>
        <li>
          <p>
            <strong>Service</strong> refers to the Website.
          </p>
        </li>
        <li>
          <p>
            <strong>Service Provider</strong> means any person or company who
            processes data on behalf of the Developer. This includes third-party
            companies or individuals I employ to facilitate the Service, provide
            it on my behalf, or assist me in analyzing how the Service is used.
          </p>
        </li>
        <li>
          <p>
            <strong>Third-party Social Media Service</strong> refers to any
            website or social network through which a User can log in or create
            an account to use the Service.
          </p>
        </li>
        <li>
          <p>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by using the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </p>
        </li>
        <li>
          <p>
            {/* TODO: Change "[Your Project Name]" and the URL to your actual project details. */}
            <strong>Website</strong> refers to Sudan Codex, accessible from{" "}
            <a
              href='https://sudan-codex.firebaseapp.com' // TODO: Update this URL
              rel='external nofollow noopener'
              target='_blank'>
              https://sudancodex.app
            </a>
          </p>
        </li>
        <li>
          <p>
            <strong>You</strong> means the individual accessing or using the
            Service.
          </p>
        </li>
      </ul>

      <h2 className='mt-8 mb-4 text-2xl font-semibold'>
        Collecting and Using Your Personal Data
      </h2>
      <h3>Types of Data Collected</h3>
      <h4>Personal Data</h4>
      <p>
        While using My Service, I may ask You to provide certain personally
        identifiable information. This may include, but is not limited to:
      </p>
      <ul className='mb-6 list-disc space-y-4 pl-6'>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Usage Data</li>
      </ul>

      <h4>Information from Third-Party Social Media Services</h4>
      <p>
        I allow You to create an account and log in to use the Service through
        the following Third-party Social Media Services:
      </p>
      <ul className='mb-6 list-disc space-y-4 pl-6'>
        <li>Google</li>
        <li>Facebook</li>
      </ul>
      <p>
        If You register through or grant me access to a Third-Party Social Media
        Service, I may collect Personal Data already associated with Your
        account, such as Your name and email address. You are giving me
        permission to use, share, and store this data in a manner consistent
        with this Privacy Policy.
      </p>

      <h4>Usage Data & Analytics</h4>
      <p>Usage Data is collected automatically when using the Service.</p>
      <p>
        This data may include your Device's IP address, browser type, browser
        version, the pages of our Service You visit, the time and date of Your
        visit, time spent on pages, and other diagnostic data.
      </p>
      <p>
        To analyze this Usage Data and improve the Service, I use the following
        Service Provider:
      </p>
      <ul className='mb-6 list-disc space-y-4 pl-6'>
        <li>
          <p>
            <strong>PostHog</strong>: I use PostHog for product analytics to
            understand user behavior and improve the Service. For more
            information on the privacy practices of PostHog, please visit the{" "}
            <a
              href='https://posthog.com/privacy'
              target='_blank'
              rel='noopener noreferrer'>
              PostHog Privacy Policy
            </a>
            .
          </p>
        </li>
      </ul>
      <h4>Tracking Technologies and Cookies</h4>
      <p>
        I use Cookies and similar tracking technologies to track activity on My
        Service and store certain information. You can instruct Your browser to
        refuse all Cookies or to indicate when a Cookie is being sent. However,
        if You do not accept Cookies, You may not be able to use some parts of
        our Service.
      </p>
      {/* This section remains largely the same as it's standard cookie practice */}
      {/* ... [Rest of the policy from "Use of Your Personal Data" onwards] ... */}

      <h2 className='mt-8 mb-4 text-2xl font-semibold'>Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, You can contact me:
      </p>
      <ul className='mb-6 list-disc space-y-4 pl-6'>
        {/* TODO: Update this email to your professional contact email. */}
        <li>By email: mohammedjrt@gmail.com</li>
      </ul>
    </main>
  );
};

export default Policy;
