// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  translation: {
    about: {
      contactTitle: "Contact";
      dataSourceDescription: "The Sudan drug index data was extracted from the";
      dataSourceLinkText: "National Medicines and Poisons Board report";
      dataSourceTitle: "Data Sources";
      dataSourceYear: "from 2023.";
      developerDescription: "Developed by Mohammed Mahmoud — Pharmacist & hobbyist coder.";
      developerTitle: "Developer";
      logoDesignerTitle: "Logo Designer";
      logos: "Available App Logos";
      nameofDesigner: "Fuad Obed";
      privacyPolicy: "Privacy Policy";
      purposeDescription: "This app helps pharmacists and healthcare professionals in Sudan is about registered drug brands, their generics, and manufacturers — creating a community-driven national drug registry.";
      purposeTitle: "Purpose";
      rightsReserved: "All rights reserved.";
      socialTitle: "Social";
      title: "About This App";
      versionTitle: "Version";
    };
    auth: {
      subtitle: "The comprehensive drug index for healthcare professionals";
      title: "Sign up or Log in";
      welcome: "Welcome!";
    };
    common: {
      error: "Error";
      success: "Success";
    };
    completeProfile: {
      age: {
        placeholder: "Enter your age";
        title: "Age";
      };
      description: "Please complete your profile information.";
      name: {
        placeholder: "Enter your name";
        title: "Name";
      };
      occupation: {
        options: {
          administrator: "Administrator";
          medicalRep: "Medical Representative";
          other: "Other";
          pharmacist: "Pharmacist";
          student: "Student";
        };
        placeholder: "Select occupation";
        selectLabel: "Select your occupation";
        title: "Occupation";
      };
      phoneNumber: {
        placeholder: "Enter your phone number";
        title: "Phone Number";
      };
      specialty: {
        options: {
          alliedHealth: "Allied Health Professional";
          doctor: "Doctor";
          nurse: "Nurse";
          other: "Other";
          pharmacist: "Pharmacist";
        };
        placeholder: "Select specialty";
        selectLabel: "Select your specialty";
        title: "Specialty";
      };
      submit: "Save Changes";
      title: "Account Information";
      university: {
        placeholder: "Enter your university";
        title: "University";
      };
      workPlace: {
        placeholder: "Enter your work place";
        title: "Work Place";
      };
    };
    drugInfo: {
      accordion: {
        administration: "Administration";
        adultDose: "Adult Dose";
        classification: "Classification";
        clinicalUse: "Clinical use";
        contraindications: "Contraindications";
        indications: "Indications";
        majorInteractions: "Major Interactions";
        mechanismOfAction: "Mechanism of Action";
        minorInteractions: "Minor Interactions";
        pediatricDose: "Pediatric Dose";
        pregnancy: "Pregnancy";
        sideEffects: "Side Effects";
      };
      agent: "Agent";
      companyName: "Company Name";
      countryOfOrigin: "Country of Origin";
      disclaimer: "Disclaimer";
      disclaimerDescription: "This app provides drug information for<1> reference only</1>. It is not a substitute for professional judgment or official product literature. Always verify details before prescribing or dispensing.";
      dosageForm: "Dosage Form";
      errorLoading: "Error loading data";
      genericName: "Generic Name";
      noDataAvailable: "No Data Available";
      noDetailsFound: "No details found for {{genericName}}";
      packSize: "Pack Size";
      strength: "Strength";
      sudanDrugIndexNote: "Note: The Sudan drug index data provided may contain formatting errors, and some information could be inaccurate. Please review the details below carefully. If any information does not match your records, disregard it.";
    };
    drugList: {
      noMoreResults: "No more results";
      searchTerm: "Search Term";
      title: "Drug List";
    };
    settings: {
      account: {
        alertMessage: "This action cannot be undone.";
        alertTitle: "Are you sure you want to delete your account?";
        cancelBtn: "Cancel";
        delete: "Delete Account";
        deleteBtn: "Delete";
        signOut: "Sign Out";
      };
      cardInformation: "Card Information";
      cardInformationDescription: "Press on the text to get the information";
      changeLanguage: "Change Language";
      changeTheme: "Change Theme";
      header: "Settings";
      help: {
        whatsApp: {
          btn: "Want help? contact me on WhatsApp";
          message: "Explain the problem and please provide any screenshot";
        };
      };
      languageChange: "The language has been changed to {{lang}}";
      restartNow: "Restart Now";
      restartRequired: "The app needs to be restarted to apply the changes";
      screens: {
        about: "About";
        account: "Account";
        advertise: "Advertise with us";
        appearanceAndLang: "Appearance and Language";
        help: "Help";
        statistics: "Statistics";
      };
      tooltips: {
        brandAndStrength: "This is the brand/trade name and the concentration/strength";
        distributor: "This is the agent name i.e. the distributor. for example Amipharma";
        dosageForm: "This is the dosage form, e.g. tablet, capsule, suspension, etc.";
        genericName: "This is the generic/scientific name";
        manufacturer: "This is the company name, i.e. the manufacturer";
        origin: "This is the country of origin";
        packSize: "This is the pack size, i.e. the amount of tablet in the box";
      };
    };
    stats: {
      associations: {
        agents: "Agents";
        companies: "Companies";
        generics: "Generics";
      };
      header: {
        subtitle: "Sudan Codex Stats";
        title: "Drug Index Statistics";
      };
      sections: {
        distributionSubtitle: "Detailed breakdown of market leaders across categories";
        distributionTitle: "Distribution & Rankings";
        topAgents: "Top Agents";
        topCompanies: "Top Companies";
        topGenerics: "Top Generic Medications";
      };
      status: {
        errorAgent: "Failed to load agent information. Please try again.";
        errorCompany: "Failed to load company information. Please try again.";
        errorGeneric: "Failed to load generic information. Please try again.";
        loadingAgent: "Loading agent details...";
        loadingCompany: "Loading company details...";
        loadingGeneric: "Loading generic details...";
        noDataAgent: "No agent data available for this entry.";
        noDataCompany: "No company data available for this entry.";
        noDataGeneric: "No generic data available for this entry.";
      };
      summary: {
        agents: "Agents";
        brandNames: "Brand Names";
        companies: "Companies";
        generics: "Generics";
        totalDrugs: "Total Drugs";
      };
      table: {
        associated: "Associated {{association}}";
        headers: {
          addedOn: "Added On";
          agent: "Agent";
          brand: "Brand";
          company: "Company";
          count: "Count";
          drugs: "Drugs";
          generic: "Generic";
          lastUpdated: "Last Updated";
          name: "Name";
          pack: "Pack";
          represented: "Represented";
          variations: "Variations";
          viewCount: "View Count";
        };
        metric: "Metric";
        overview: "Statistics Overview";
        totalDrugsRepresented: "Total Drugs Represented";
      };
    };
    tabs: {
      drugList: "Drug List";
      settings: "Settings";
    };
  };
}

export default Resources;
