import Header from "@/components/layout/header";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AuthProvider } from "@/hooks/useAuth";
import { PHProvider } from "@/providers/PHProvider";
import TanstackQueryProvider from "@/providers/query-client";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import Footer from "@/components/layout/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <PHProvider>
          <TanstackQueryProvider>
            {process.env.DEV && (
              <Suspense fallback={null}>
                <ReactQueryDevtools initialIsOpen={false} />
              </Suspense>
            )}
            <SidebarProvider
              className='flex-col'
              defaultOpen={false}>
              <ThemeProvider
                defaultTheme='dark'
                storageKey='vite-ui-theme'>
                <AuthProvider>
                  <Header />
                  {children}
                  <Footer />
                </AuthProvider>
              </ThemeProvider>
            </SidebarProvider>
          </TanstackQueryProvider>
        </PHProvider>
      </body>
    </html>
  );
}
