import { Metadata } from "next";
import type { JSX } from "react";

export const metadata: Metadata = {
  title: "Privacy Policy | Sudan Codex",
  description:
    "Read the Privacy Policy of Sudan Codex to understand how we collect, use, and protect your personal information while you access Sudan's comprehensive drug index.",
  alternates: {
    canonical: "/privacy-policy",
  },
};

const Policy = (): JSX.Element => {
  return (
    <div className='container mx-auto max-w-4xl px-4 py-8'>
      <h1 className='mb-4 text-3xl font-bold'>Privacy Policy</h1>
      <p>Last updated: November 18, 2025</p>
      <p>
        This Privacy Policy describes my policies and procedures on the
        collection, use, and disclosure of Your information when You use the
        Service. It also tells You about Your privacy rights and how the law
        protects You.
      </p>
      <p>
        I use Your Personal Data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>
      <h2 className='mt-8 mb-4 text-2xl font-semibold'>
        Interpretation and Definitions
      </h2>
      <h3 className='mb-2 text-xl font-semibold'>Interpretation</h3>
      <p>
        Words with an initial capital letter have meanings defined under the
        following conditions. These definitions have the same meaning regardless
        of whether they appear in singular or plural form.
      </p>
      <h3 className='mb-2 text-xl font-semibold'>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul className='mb-6 list-disc space-y-4 pl-6'>
        <li>
          <p>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </p>
        </li>
        <li>
          <p>
            <strong>Developer</strong> (referred to as either &quot;I&quot;,
            &quot;Me&quot;, or &quot;My&quot; in this Agreement) refers to Sudan
            Codex.
          </p>
        </li>
        <li>
          <p>
            <strong>Cookies</strong> are small files placed on Your computer or
            device by a website, containing details of Your Browse history.
          </p>
        </li>
        <li>
          <p>
            <strong>Device</strong> means any device that can access the
            Service, such as a computer, a cellphone, or a digital tablet.
          </p>
        </li>
        <li>
          <p>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </p>
        </li>
        <li>
          <p>
            <strong>Service</strong> refers to the Website.
          </p>
        </li>
        <li>
          <p>
            <strong>Service Provider</strong> means any person or company who
            processes data on behalf of the Developer. This includes third-party
            companies or individuals I employ to facilitate the Service, provide
            it on my behalf, or assist me in analyzing how the Service is used.
          </p>
        </li>
        <li>
          <p>
            <strong>Third-party Social Media Service</strong> refers to any
            website or social network through which a User can log in or create
            an account to use the Service.
          </p>
        </li>
        <li>
          <p>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by using the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </p>
        </li>
        <li>
          <p>
            <strong>Website</strong> refers to Sudan Codex, accessible from{" "}
            <a
              href='https://sudancodex.app'
              rel='external nofollow noopener noreferrer'
              target='_blank'>
              https://sudancodex.app
            </a>
          </p>
        </li>
        <li>
          <p>
            <strong>You</strong> means the individual accessing or using the
            Service.
          </p>
        </li>
      </ul>
      <h2 className='mt-8 mb-4 text-2xl font-semibold'>
        Collecting and Using Your Personal Data
      </h2>
      <h3 className='mb-2 text-xl font-semibold'>Types of Data Collected</h3>
      <h4 className='mb-2 text-lg font-semibold'>Personal Data</h4>
      <p>
        While using My Service, I may ask You to provide certain personally
        identifiable information. This may include, but is not limited to:
      </p>
      <ul className='mb-6 list-disc space-y-4 pl-6'>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Usage Data</li>
      </ul>
      <h4 className='mb-2 text-lg font-semibold'>
        Information from Third-Party Social Media Services
      </h4>
      <p>
        I allow You to create an account and log in to use the Service through
        the following Third-party Social Media Services:
      </p>
      <ul className='mb-6 list-disc space-y-4 pl-6'>
        <li>Google</li>
        <li>Facebook</li>
      </ul>
      <p>
        If You register through or grant me access to a Third-Party Social Media
        Service, I may collect Personal Data already associated with Your
        account, such as Your name and email address. You are giving me
        permission to use, share, and store this data in a manner consistent
        with this Privacy Policy.
      </p>
      <h4 className='mb-2 text-lg font-semibold'>Usage Data & Analytics</h4>
      <p>Usage Data is collected automatically when using the Service.</p>
      <p>
        This data may include your Device&apos;s IP address, browser type,
        browser version, the pages of our Service You visit, the time and date
        of Your visit, time spent on pages, and other diagnostic data.
      </p>
      <p>
        PostHog may process limited personal data such as user identifiers
        (e.g., internal user ID or email address) to provide analytics services
        on our behalf.
      </p>
      <p>
        To analyze this Usage Data and improve the Service, I use the following
        Service Provider:
      </p>
      <ul className='mb-6 list-disc space-y-4 pl-6'>
        <li>
          <p>
            <strong>PostHog</strong>: I use PostHog for product analytics to
            understand user behavior and improve the Service. For more
            information on the privacy practices of PostHog, please visit the{" "}
            <a
              className='underline'
              href='https://posthog.com/privacy'
              target='_blank'
              rel='noopener noreferrer'>
              PostHog Privacy Policy
            </a>
            .
          </p>
        </li>
      </ul>
      <h4 className='mb-2 text-lg font-semibold'>
        Tracking Technologies and Cookies
      </h4>
      <p>
        I use Cookies and similar tracking technologies to track activity on My
        Service and store certain information. You can instruct Your browser to
        refuse all Cookies or to indicate when a Cookie is being sent. However,
        if You do not accept Cookies, You may not be able to use some parts of
        our Service.
      </p>
      {/* This section remains largely the same as it's standard cookie practice */}
      {/* ... [Rest of the policy from "Use of Your Personal Data" onwards] ... */}
      <h3 className='mb-2 text-xl font-semibold'>Use of Your Personal Data</h3>{" "}
      <p>The Developer may use Personal Data for the following purposes: </p>{" "}
      <ul className='mb-6 list-disc space-y-4 pl-6'>
        {" "}
        <li>
          {" "}
          <p>
            {" "}
            <strong className='font-medium'>
              To provide and maintain our Service{" "}
            </strong>
            , including to monitor the usage of our Service.{" "}
          </p>{" "}
        </li>{" "}
        <li>
          {" "}
          <p>
            {" "}
            <strong className='font-medium'>
              To manage Your Account:
            </strong> to
            manage Your registration as a user of the Service. The Personal Data
            You provide can give You access to different functionalities of the
            Service that are available to You as a registered user.{" "}
          </p>{" "}
        </li>{" "}
        <li>
          {" "}
          <p>
            {" "}
            <strong className='font-medium'>
              For the performance of a contract:{" "}
            </strong>{" "}
            the development, compliance and undertaking of the purchase contract
            for the products, items or services You have purchased or of any
            other contract with Me through the Service.{" "}
          </p>{" "}
        </li>{" "}
        <li>
          {" "}
          <p>
            <strong className='font-medium'>To contact You:</strong> To contact
            You by email, telephone calls, SMS, or other equivalent forms of
            electronic communication, such as a mobile application&apos;s push
            notifications regarding updates or informative communications
            related to the functionalities, products or contracted services,
            including the security updates, when necessary or reasonable for
            their implementation.{" "}
          </p>{" "}
        </li>{" "}
        <li>
          {" "}
          <p>
            <strong className='font-medium'>To provide You</strong> with news,
            special offers and general information about other goods, services
            and events which we offer that are similar to those that you have
            already purchased or enquired about unless You have opted not to
            receive such information.{" "}
          </p>{" "}
        </li>{" "}
        <li>
          {" "}
          <p>
            {" "}
            <strong className='font-medium'>
              To manage Your requests:
            </strong> To
            attend and manage Your requests to Me.{" "}
          </p>{" "}
        </li>{" "}
        <li>
          {" "}
          <p>
            {" "}
            <strong className='font-medium'>
              For business transfers:
            </strong> We
            may use Your information to evaluate or conduct a merger,
            divestiture, restructuring, reorganization, dissolution, or other
            sale or transfer of some or all of My assets, whether as a going
            concern or as part of bankruptcy, liquidation, or similar
            proceeding, in which Personal Data held by Me about our Service
            users is among the assets transferred.{" "}
          </p>{" "}
        </li>{" "}
        <li>
          {" "}
          <p>
            {" "}
            <strong className='font-medium'>For other purposes</strong>: We may
            use Your information for other purposes, such as data analysis,
            identifying usage trends, determining the effectiveness of our
            promotional campaigns and to evaluate and improve our Service,
            products, services, marketing and your experience.{" "}
          </p>{" "}
        </li>{" "}
      </ul>{" "}
      <p>
        We may share Your personal information in the following situations:{" "}
      </p>{" "}
      <ul className='mb-6 list-disc space-y-4 pl-6'>
        {" "}
        <li>
          {" "}
          <strong className='font-medium'>With Service Providers:</strong> We
          may share Your personal information with Service Providers to monitor
          and analyze the use of our Service, to contact You.{" "}
        </li>{" "}
        <li>
          {" "}
          <strong className='font-medium'>For business transfers:</strong> We
          may share or transfer Your personal information in connection with, or
          during negotiations of, any merger, sale of Developer assets,
          financing, or acquisition of all or a portion of My business to
          another company.{" "}
        </li>{" "}
        <li>
          <strong className='font-medium'>With Affiliates:</strong> We may share
          Your information with My affiliates, in which case we will require
          those affiliates to honor this Privacy Policy. Affiliates include My
          parent company and any other subsidiaries, joint venture partners or
          other companies that We control or that are under common control with
          Me.{" "}
        </li>{" "}
        <li>
          {" "}
          <strong className='font-medium'>With business partners:</strong> We
          may share Your information with My business partners to offer You
          certain products, services or promotions.{" "}
        </li>{" "}
        <li>
          <strong className='font-medium'>With other users:</strong> when You
          share personal information or otherwise interact in the public areas
          with other users, such information may be viewed by all users and may
          be publicly distributed outside. If You interact with other users or
          register through a Third-Party Social Media Service, Your contacts on
          the Third-Party Social Media Service may see Your name, profile,
          pictures and description of Your activity. Similarly, other users will
          be able to view descriptions of Your activity, communicate with You
          and view Your profile.{" "}
        </li>{" "}
        <li>
          <strong className='font-medium'>With Your consent</strong>: We may
          disclose Your personal information for any other purpose with Your
          consent.{" "}
        </li>{" "}
      </ul>
      <h3 className='mb-2 text-xl font-semibold'>
        Retention of Your Personal Data
      </h3>{" "}
      <p>
        The Developer will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use Your Personal Data to the extent necessary to comply with
        our legal obligations (for example, if we are required to retain your
        data to comply with applicable laws), resolve disputes, and enforce our
        legal agreements and policies.{" "}
      </p>{" "}
      <p>
        The Developer will also retain Usage Data for internal analysis
        purposes. Usage Data is generally retained for a shorter period of time,
        except when this data is used to strengthen the security or to improve
        the functionality of My Service, or We are legally obligated to retain
        this data for longer time periods.{" "}
      </p>
      <h3 className='mb-2 text-xl font-semibold'>
        Transfer of Your Personal Data
      </h3>{" "}
      <p>
        Your information, including Personal Data, is processed at the
        Company&apos;s operating offices and in any other places where the
        parties involved in the processing are located. It means that this
        information may be transferred to — and maintained on — computers
        located outside of Your state, province, country or other governmental
        jurisdiction where the data protection laws may differ than those from
        Your jurisdiction.{" "}
      </p>{" "}
      <p>
        Your consent to this Privacy Policy followed by Your submission of such
        information represents Your agreement to that transfer.{" "}
      </p>{" "}
      <p>
        The Developer will take all steps reasonably necessary to ensure that
        Your data is treated securely and in accordance with this Privacy Policy
        and no transfer of Your Personal Data will take place to an organization
        or a country unless there are adequate controls in place including the
        security of Your data and other personal information.{" "}
      </p>
      <h3 className='mb-2 text-xl font-semibold'>Delete Your Personal Data</h3>{" "}
      <p>
        You have the right to delete or request that We assist in deleting the
        Personal Data that We have collected about You.{" "}
      </p>{" "}
      <p>
        My Service may give You the ability to delete certain information about
        You from within the Service.{" "}
      </p>{" "}
      <p>
        You may update, amend, or delete Your information at any time by signing
        in to Your Account, if you have one, and visiting the account settings
        section that allows you to manage Your personal information. You may
        also contact Me to request access to, correct, or delete any personal
        information that You have provided to Me.{" "}
      </p>{" "}
      <p>
        Please note, however, that We may need to retain certain information
        when we have a legal obligation or lawful basis to do so.{" "}
      </p>
      <h3 className='mb-2 text-xl font-semibold'>
        Disclosure of Your Personal Data
      </h3>{" "}
      <h4 className='mb-2 text-xl font-semibold'>Business Transactions</h4>{" "}
      <p>
        If the Developer is involved in a merger, acquisition or asset sale,
        Your Personal Data may be transferred. We will provide notice before
        Your Personal Data is transferred and becomes subject to a different
        Privacy Policy.{" "}
      </p>
      <h4>Law enforcement</h4>{" "}
      <p>
        Under certain circumstances, the Developer may be required to disclose
        Your Personal Data if required to do so by law or in response to valid
        requests by public authorities (e.g. a court or a government
        agency).{" "}
      </p>
      <h4>Other legal requirements</h4>{" "}
      <p>
        The Developer may disclose Your Personal Data in the good faith belief
        that such action is necessary to:{" "}
      </p>{" "}
      <ul className='mb-6 list-disc space-y-4 pl-6'>
        <li>Comply with a legal obligation</li>{" "}
        <li>Protect and defend the rights or property of the Company</li>{" "}
        <li>
          Prevent or investigate possible wrongdoing in connection with the
          Service{" "}
        </li>{" "}
        <li>
          Protect the personal safety of Users of the Service or the public{" "}
        </li>
        <li>Protect against legal liability</li>{" "}
      </ul>
      <h3 className='mb-2 text-xl font-semibold'>
        Security of Your Personal Data
      </h3>{" "}
      <p>
        The security of Your Personal Data is important to Me, but remember that
        no method of transmission over the Internet, or method of electronic
        storage is 100% secure. While We strive to use commercially acceptable
        means to protect Your Personal Data, We cannot guarantee its absolute
        security.{" "}
      </p>{" "}
      <h2 className='mt-8 mb-4 text-2xl font-semibold'>
        Children&apos;s Privacy
      </h2>{" "}
      <p>
        My Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13. If You are a parent or guardian and You are aware that
        Your child has provided Me with Personal Data, please contact Me. If We
        become aware that We have collected Personal Data from anyone under the
        age of 13 without verification of parental consent, We take steps to
        remove that information from My servers.{" "}
      </p>{" "}
      <p>
        If We need to rely on consent as a legal basis for processing Your
        information and Your country requires consent from a parent, We may
        require Your parent&apos;s consent before We collect and use that
        information.{" "}
      </p>{" "}
      <h2 className='mt-8 mb-4 text-2xl font-semibold'>
        Links to Other Websites{" "}
      </h2>{" "}
      <p>
        My Service may contain links to other websites that are not operated by
        Me. If You click on a third party link, You will be directed to that
        third party&apos;s site. We strongly advise You to review the Privacy
        Policy of every site You visit.{" "}
      </p>{" "}
      <p>
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.{" "}
      </p>{" "}
      <h2 className='mt-8 mb-4 text-2xl font-semibold'>
        Changes to this Privacy Policy{" "}
      </h2>{" "}
      <p>
        We may update My Privacy Policy from time to time. We will notify You of
        any changes by posting the new Privacy Policy on this page.{" "}
      </p>{" "}
      <p>
        We will let You know via email and/or a prominent notice on My Service,
        prior to the change becoming effective and update the &quot;Last
        updated&quot; date at the top of this Privacy Policy.{" "}
      </p>{" "}
      <p>
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.{" "}
      </p>
      <h2 className='mt-8 mb-4 text-2xl font-semibold'>Contact Me</h2>
      <p>
        If you have any questions about this Privacy Policy, You can contact me:
      </p>
      <ul className='mb-6 list-disc space-y-4 pl-6'>
        {/* TODO: Update this email to your professional contact email. */}
        <li>By email: mohammedjrt@gmail.com</li>
      </ul>
    </div>
  );
};

export default Policy;
