import Footer from "@/src/components/layout/Footer";
import { AppSidebar } from "@/src/components/layout/app-sidebar";
import Header from "@/src/components/layout/header";
import { SidebarInset, SidebarProvider } from "@/src/components/ui/sidebar";
import { AuthProvider } from "@/src/hooks/useAuth";
import { PHProvider } from "@/src/providers/PHProvider";
import TanstackQueryProvider from "@/src/providers/query-client";
import { ThemeProvider } from "@/src/providers/theme-provider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { Suspense } from "react";
import DrugInitializer from "../components/initDexieDb";
import "./globals.css";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PHProvider>
          <TanstackQueryProvider>
            {process.env.NODE_ENV === "development" && (
              <Suspense fallback={null}>
                <ReactQueryDevtools initialIsOpen={false} />
              </Suspense>
            )}
            <ThemeProvider
              attribute='class'
              defaultTheme='system'
              enableSystem
              disableTransitionOnChange>
              <AuthProvider>
                <SidebarProvider defaultOpen={false}>
                  <AppSidebar />
                  <SidebarInset>
                    <Header />
                    <main className='flex-1'>{children}</main>
                    <Footer />
                    <DrugInitializer />
                  </SidebarInset>
                </SidebarProvider>
              </AuthProvider>
            </ThemeProvider>
          </TanstackQueryProvider>
        </PHProvider>
      </body>
    </html>
  );
}
