import Footer from "@/src/components/layout/Footer";
import { AppSidebar } from "@/src/components/layout/app-sidebar";
import Header from "@/src/components/layout/header";
import { SidebarInset, SidebarProvider } from "@/src/components/ui/sidebar";
import { AuthProvider } from "@/src/hooks/useAuth";
import { PHProvider } from "@/src/providers/PHProvider";
import TanstackQueryProvider from "@/src/providers/query-client";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import { ThemeProvider } from "@/src/providers/theme-provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <PHProvider>
          <TanstackQueryProvider>
            {process.env.DEV && (
              <Suspense fallback={null}>
                <ReactQueryDevtools initialIsOpen={false} />
              </Suspense>
            )}
            <ThemeProvider
              attribute='class'
              defaultTheme='system'
              enableSystem
              disableTransitionOnChange>
              <AuthProvider>
                <SidebarProvider defaultOpen={false}>
                  <AppSidebar />
                  <SidebarInset>
                    <Header />

                    <div className='flex min-h-screen flex-col'>
                      <main className='flex-1'>{children}</main>
                      <Footer />
                    </div>
                  </SidebarInset>
                </SidebarProvider>
              </AuthProvider>
            </ThemeProvider>
          </TanstackQueryProvider>
        </PHProvider>
      </body>
    </html>
  );
}
