import { DosageForm, Unit } from "./types/types";

export const drugConcentrationUnits: Unit[] = [
  { value: "mg", label: "mg" },
  { value: "g", label: "g" },
  { value: "mcg", label: "mcg" },
  { value: "ng", label: "ng" },
  { value: "U", label: "U" },
  { value: "IU", label: "IU" },
  { value: "kg", label: "kg" },
  { value: "mL", label: "mL" },
  { value: "L", label: "L" },
  { value: "% w/w", label: "% w/w" },
  { value: "% w/v", label: "% w/v" },
  { value: "% v/v", label: "% v/v" },
  { value: "%", label: "%" },
  { value: "other", label: "Other" },
];

export const dosageForms: DosageForm[] = [
  { value: "aerosol", label: "AEROSOL" },
  { value: "aerosolFoam", label: "AEROSOL, FOAM" },
  { value: "aerosolMetered", label: "AEROSOL, METERED" },
  { value: "aerosolPowder", label: "AEROSOL, POWDER" },
  { value: "aerosolSpray", label: "AEROSOL, SPRAY" },
  { value: "barChewable", label: "BAR, CHEWABLE" },
  { value: "bead", label: "BEAD" },
  { value: "capsule", label: "CAPSULE" },
  { value: "capsuleCoated", label: "CAPSULE, COATED" },
  { value: "capsuleCoatedPellets", label: "CAPSULE, COATED PELLETS" },
  {
    value: "capsuleCoatedExtendedRelease",
    label: "CAPSULE, COATED, EXTENDED RELEASE",
  },
  { value: "capsuleDelayedRelease", label: "CAPSULE, DELAYED RELEASE" },
  {
    value: "capsuleDelayedReleasePellets",
    label: "CAPSULE, DELAYED RELEASE PELLETS",
  },
  { value: "capsuleExtendedRelease", label: "CAPSULE, EXTENDED RELEASE" },
  {
    value: "capsuleFilmCoatedExtendedRelease",
    label: "CAPSULE, FILM COATED, EXTENDED RELEASE",
  },
  { value: "capsuleGelatinCoated", label: "CAPSULE, GELATIN COATED" },
  { value: "capsuleLiquidFilled", label: "CAPSULE, LIQUID FILLED" },
  { value: "cellularSheet", label: "CELLULAR SHEET" },
  { value: "chewableGel", label: "CHEWABLE GEL" },
  { value: "cloth", label: "CLOTH" },
  { value: "concentrate", label: "CONCENTRATE" },
  { value: "cream", label: "CREAM" },
  { value: "creamAugmented", label: "CREAM, AUGMENTED" },
  { value: "crystal", label: "CRYSTAL" },
  { value: "disc", label: "DISC" },
  { value: "douche", label: "DOUCHE" },
  { value: "dressing", label: "DRESSING" },
  { value: "drugElutingContactLens", label: "DRUG-ELUTING CONTACT LENS" },
  { value: "elixir", label: "ELIXIR" },
  { value: "emulsion", label: "EMULSION" },
  { value: "enema", label: "ENEMA" },
  { value: "extract", label: "EXTRACT" },
  { value: "fiberExtendedRelease", label: "FIBER, EXTENDED RELEASE" },
  { value: "film", label: "FILM" },
  { value: "filmExtendedRelease", label: "FILM, EXTENDED RELEASE" },
  { value: "filmSoluble", label: "FILM, SOLUBLE" },
  { value: "forSolution", label: "FOR SOLUTION" },
  { value: "forSuspension", label: "FOR SUSPENSION" },
  {
    value: "forSuspensionExtendedRelease",
    label: "FOR SUSPENSION, EXTENDED RELEASE",
  },
  { value: "gas", label: "GAS" },
  { value: "gel", label: "GEL" },
  { value: "gelDentifrice", label: "GEL, DENTIFRICE" },
  { value: "gelMetered", label: "GEL, METERED" },
  { value: "globule", label: "GLOBULE" },
  { value: "granule", label: "GRANULE" },
  { value: "granuleDelayedRelease", label: "GRANULE, DELAYED RELEASE" },
  { value: "granuleEffervalueescent", label: "GRANULE, EFFERValueESCENT" },
  { value: "granuleForSolution", label: "GRANULE, FOR SOLUTION" },
  { value: "granuleForSuspension", label: "GRANULE, FOR SUSPENSION" },
  {
    value: "granuleForSuspensionExtendedRelease",
    label: "GRANULE, FOR SUSPENSION, EXTENDED RELEASE",
  },
  { value: "gumChewing", label: "GUM, CHEWING" },
  { value: "implant", label: "IMPLANT" },
  { value: "inhalant", label: "INHALANT" },
  { value: "injectableFoam", label: "INJECTABLE FOAM" },
  { value: "injectableLiposomal", label: "INJECTABLE, LIPOSOMAL" },
  { value: "injection", label: "INJECTION" },
  { value: "injectionEmulsion", label: "INJECTION, EMULSION" },
  { value: "injectionLipidComplex", label: "INJECTION, LIPID COMPLEX" },
  {
    value: "injectionPowderForSolution",
    label: "INJECTION, POWDER, FOR SOLUTION",
  },
  {
    value: "injectionPowderForSuspension",
    label: "INJECTION, POWDER, FOR SUSPENSION",
  },
  {
    value: "injectionPowderForSuspensionExtendedRelease",
    label: "INJECTION, POWDER, FOR SUSPENSION, EXTENDED RELEASE",
  },
  {
    value: "injectionPowderLyophilizedForLiposomalSuspension",
    label: "INJECTION, POWDER, LYOPHILIZED, FOR LIPOSOMAL SUSPENSION",
  },
  {
    value: "injectionPowderLyophilizedForSolution",
    label: "INJECTION, POWDER, LYOPHILIZED, FOR SOLUTION",
  },
  {
    value: "injectionPowderLyophilizedForSuspension",
    label: "INJECTION, POWDER, LYOPHILIZED, FOR SUSPENSION",
  },
  {
    value: "injectionPowderLyophilizedForSuspensionExtendedRelease",
    label: "INJECTION, POWDER, LYOPHILIZED, FOR SUSPENSION, EXTENDED RELEASE",
  },
  { value: "injectionSolution", label: "INJECTION, SOLUTION" },
  {
    value: "injectionSolutionConcentrate",
    label: "INJECTION, SOLUTION, CONCENTRATE",
  },
  { value: "injectionSuspension", label: "INJECTION, SUSPENSION" },
  {
    value: "injectionSuspensionExtendedRelease",
    label: "INJECTION, SUSPENSION, EXTENDED RELEASE",
  },
  {
    value: "injectionSuspensionLiposomal",
    label: "INJECTION, SUSPENSION, LIPOSOMAL",
  },
  {
    value: "injectionSuspensionSonicated",
    label: "INJECTION, SUSPENSION, SONICATED",
  },
  { value: "insert", label: "INSERT" },
  { value: "insertExtendedRelease", label: "INSERT, EXTENDED RELEASE" },
  { value: "intrauterineDevice", label: "INTRAUTERINE DEVICE" },
  { value: "irrigant", label: "IRRIGANT" },
  { value: "jelly", label: "JELLY" },
  { value: "kit", label: "KIT" },
  { value: "liniment", label: "LINIMENT" },
  { value: "lipstick", label: "LIPSTICK" },
  { value: "liquid", label: "LIQUID" },
  { value: "liquidExtendedRelease", label: "LIQUID, EXTENDED RELEASE" },
  { value: "lotion", label: "LOTION" },
  { value: "lotionAugmented", label: "LOTION, AUGMENTED" },
  { value: "lotionShampoo", label: "LOTION/SHAMPOO" },
  { value: "lozenge", label: "LOZENGE" },
  { value: "mouthwash", label: "MOUTHWASH" },
  { value: "notApplicable", label: "NOT APPLICABLE" },
  { value: "oil", label: "OIL" },
  { value: "ointment", label: "OINTMENT" },
  { value: "ointmentAugmented", label: "OINTMENT, AUGMENTED" },
  { value: "paste", label: "PASTE" },
  { value: "pasteDentifrice", label: "PASTE, DENTIFRICE" },
  { value: "pastille", label: "PASTILLE" },
  { value: "patch", label: "PATCH" },
  { value: "patchExtendedRelease", label: "PATCH, EXTENDED RELEASE" },
  {
    value: "patchExtendedReleaseElectricallyControlled",
    label: "PATCH, EXTENDED RELEASE, ELECTRICALLY CONTROLLED",
  },
  { value: "pellet", label: "PELLET" },
  { value: "pelletImplantable", label: "PELLET, IMPLANTABLE" },
  {
    value: "pelletsCoatedExtendedRelease",
    label: "PELLETS, COATED, EXTENDED RELEASE",
  },
  { value: "pill", label: "PILL" },
  { value: "plaster", label: "PLASTER" },
  { value: "poultice", label: "POULTICE" },
  { value: "powder", label: "POWDER" },
  { value: "powderDentifrice", label: "POWDER, DENTIFRICE" },
  { value: "powderForSolution", label: "POWDER, FOR SOLUTION" },
  { value: "powderForSuspension", label: "POWDER, FOR SUSPENSION" },
  { value: "powderMetered", label: "POWDER, METERED" },
  { value: "ring", label: "RING" },
  { value: "rinse", label: "RINSE" },
  { value: "salve", label: "SALVE" },
  { value: "shampoo", label: "SHAMPOO" },
  { value: "shampooSuspension", label: "SHAMPOO, SUSPENSION" },
  { value: "soap", label: "SOAP" },
  { value: "solution", label: "SOLUTION" },
  { value: "solutionConcentrate", label: "SOLUTION, CONCENTRATE" },
  { value: "solutionForSlush", label: "SOLUTION, FOR SLUSH" },
  { value: "solutionGelFormingDrops", label: "SOLUTION, GEL FORMING / DROPS" },
  {
    value: "solutionGelFormingExtendedRelease",
    label: "SOLUTION, GEL FORMING, EXTENDED RELEASE",
  },
  { value: "solutionDrops", label: "SOLUTION/ DROPS" },
  { value: "sponge", label: "SPONGE" },
  { value: "spray", label: "SPRAY" },
  { value: "sprayMetered", label: "SPRAY, METERED" },
  { value: "spraySuspension", label: "SPRAY, SUSPENSION" },
  { value: "stick", label: "STICK" },
  { value: "strip", label: "STRIP" },
  { value: "suppository", label: "SUPPOSITORY" },
  {
    value: "suppositoryExtendedRelease",
    label: "SUPPOSITORY, EXTENDED RELEASE",
  },
  { value: "suspension", label: "SUSPENSION" },
  { value: "suspensionExtendedRelease", label: "SUSPENSION, EXTENDED RELEASE" },
  { value: "suspensionDrops", label: "SUSPENSION/ DROPS" },
  { value: "swab", label: "SWAB" },
  { value: "syrup", label: "SYRUP" },
  { value: "system", label: "SYSTEM" },
  { value: "tablet", label: "TABLET" },
  { value: "tabletChewable", label: "TABLET, CHEWABLE" },
  {
    value: "tabletChewableExtendedRelease",
    label: "TABLET, CHEWABLE, EXTENDED RELEASE",
  },
  { value: "tabletCoated", label: "TABLET, COATED" },
  { value: "tabletCoatedParticles", label: "TABLET, COATED PARTICLES" },
  { value: "tabletDelayedRelease", label: "TABLET, DELAYED RELEASE" },
  {
    value: "tabletDelayedReleaseParticles",
    label: "TABLET, DELAYED RELEASE PARTICLES",
  },
  { value: "tabletEffervescent", label: "TABLET, EFFERVESCENT" },
  { value: "tabletExtendedRelease", label: "TABLET, EXTENDED RELEASE" },
  { value: "tabletFilmCoated", label: "TABLET, FILM COATED" },
  {
    value: "tabletFilmCoatedExtendedRelease",
    label: "TABLET, FILM COATED, EXTENDED RELEASE",
  },
  { value: "tabletForSolution", label: "TABLET, FOR SOLUTION" },
  { value: "tabletForSuspension", label: "TABLET, FOR SUSPENSION" },
  { value: "tabletMultilayer", label: "TABLET, MULTILAYER" },
  {
    value: "tabletMultilayerExtendedRelease",
    label: "TABLET, MULTILAYER, EXTENDED RELEASE",
  },
  {
    value: "tabletOrallyDisintegrating",
    label: "TABLET, ORALLY DISINTEGRATING",
  },
  {
    value: "tabletOrallyDisintegratingDelayedRelease",
    label: "TABLET, ORALLY DISINTEGRATING, DELAYED RELEASE",
  },
  { value: "tabletSoluble", label: "TABLET, SOLUBLE" },
  { value: "tabletSugarCoated", label: "TABLET, SUGAR COATED" },
  { value: "tabletWithSensor", label: "TABLET WITH SENSOR" },
  { value: "tampon", label: "TAMPON" },
  { value: "tape", label: "TAPE" },
  { value: "tincture", label: "TINCTURE" },
  { value: "troche", label: "TROCHE" },
  { value: "tube", label: "TUBE" },
  { value: "unitDose", label: "UNIT DOSE" },
  { value: "vaginalInsert", label: "VAGINAL INSERT" },
  { value: "vapor", label: "VAPOR" },
  { value: "wafer", label: "WAFER" },
  { value: "water", label: "WATER" },
  { value: "wax", label: "WAX" },
];

export const DRUG_PACKAGE_TYPES = [
  { value: "blister_pack", label: "Blister Pack" },
  { value: "bottle", label: "Bottle" },
  { value: "can", label: "can" },
  { value: "vial", label: "Vial" },
  { value: "syringe", label: "Syringe" },
  { value: "ampoule", label: "Ampoule" },
  { value: "infusion_bag", label: "Infusion Bag" },
  { value: "transdermal_patche", label: "Transdermal Patch" },
  { value: "tube", label: "Tube" },
  { value: "pack", label: "Pack (Box)" },
  { value: "nasal_sprays_inhaler", label: "Nasal Spray and Inhaler" },
  { value: "spray", label: "Spray" },
  {value:"cartridge", label:"Cartridge"},
  { value: "other", label: "Other" },
];
export const description =
  "A sign up form with first name, last name, email and password inside a card. There's an option to sign up with GitHub and a link to login if you already have an account";